font_family JetBrainsMono Nerd Font
font_size 12

background #060d14
foreground #b9cbd2
selection_background #172836
selection_foreground #d6e3e7
cursor #7fb6c9
cursor_shape beam
cursor_blink_interval 0

background_opacity 0.75
dynamic_background_opacity no
window_padding_width 8
hide_window_decorations yes
confirm_os_window_close 0
enable_audio_bell no

color0  #060d14
color1  #a56b73
color2  #8bbf9f
color3  #b8a36f
color4  #355d78
color5  #7f8fa6
color6  #7fb6c9
color7  #b9cbd2
color8  #172836
color9  #b77d84
color10 #9fcbb0
color11 #c3b37e
color12 #4d7892
color13 #93a1b4
color14 #93c4d3
color15 #d6e3e7
