# Hacknet-inspired Hyprland entrypoint.
# Keep this file as sources only.

source = ~/.config/hypr/conf/theme.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/workspaces.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/startup.conf
source = ~/.config/hypr/conf/binds.conf

exec-once = waybar
