general {
    gaps_in = 3
    gaps_out = 6,18,6,18
    border_size = 1
    col.active_border = $cyan $blue 35deg
    col.inactive_border = $blue_dim
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = true
    bezier = cyber, 0.16, 1, 0.3, 1
    animation = windows, 1, 2, cyber, slide
    animation = windowsOut, 1, 2, cyber, slide
    animation = border, 1, 4, cyber
    animation = fade, 1, 2, cyber
    animation = workspaces, 1, 2, cyber, slide
}

dwindle {
    preserve_split = true
    smart_split = false
    smart_resizing = true
}

master {
    new_status = master
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
}
