windowrule = match:class ^(kitty)$, opacity 0.94 0.86
windowrule = match:class ^(hacknet-boot)$, float on
windowrule = match:class ^(hacknet-boot)$, center on
windowrule = match:title ^(Open File)$, float on
windowrule = match:title ^(Save File)$, float on
windowrule = match:title ^(Picture-in-Picture)$, float on
windowrule = match:title ^(Picture-in-Picture)$, keep_aspect_ratio on
